jmuscle:
   db-properties:
     connections:
       asyncdb:
         driverClassName: com.mysql.cj.jdbc.Driver
         jdbcUrl: jdbc:mysql://localhost:3306/async-db
         username: root
         password: password
         secretKey:
         algorithm: 
     dataSources:
       asyncdb:
         type: hikari
         connectionPropsKey: asyncdb
         additionalProperties:
           poolName: 
           minimumIdle: 1
           maximumPoolSize: 5 
           maxLifetime: 0
           connectionTimeout: 180000